Remove Z3 param "seed"
It looks like the legacy parameter `seed` has been removed. If we try to pass it, `Solver.add` fails with

```
com.microsoft.z3.Z3Exception: unknown parameter 'seed'
Legal parameters are:
...
```

Only `random_seed` remains in the list.